# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "loyalty-customer-reward"
client_id = "65ed361e1b30cad533121d30ca794626"
application_url = "https://gr3-loyalty-reward.fly.dev"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_files,write_files,read_product,read_customers,write_customers,read_discounts,write_discounts,read_gift_cards,write_gift_cards,read_themes,write_themes"

[auth]
redirect_urls = [
  "https://gr3-loyalty-reward.fly.dev/auth/callback",
  "https://gr3-loyalty-reward.fly.dev/auth/shopify/callback",
  "https://gr3-loyalty-reward.fly.dev/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = false
dev_store_url = "sstrikess-test-discount-app.myshopify.com"
