# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f4cc6a39eccbcc6b3a45010d29c4d559"
name = "loyalty-customer-reward"
handle = "loyalty-customer-reward"
application_url = "https://roads-safely-controls-convenient.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "sstrikess-test-discount-app.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_products,read_shipping,write_discounts"

[auth]
redirect_urls = [
  "https://roads-safely-controls-convenient.trycloudflare.com/auth/callback",
  "https://roads-safely-controls-convenient.trycloudflare.com/auth/shopify/callback",
  "https://roads-safely-controls-convenient.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[app_proxy]
url = "https://roads-safely-controls-convenient.trycloudflare.com/auth/callback"
subpath = "frontend"
prefix = "apps"

[pos]
embedded = false
