# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c0237746d5feff0054b309baee1f1f36"
name = "thanhnt-discount-app"
handle = "thanhnt-discount-app"
application_url = "https://testimony-evaluated-lime-period.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "sstrikess-test-discount-app.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_products,read_shipping,write_discounts"

[auth]
redirect_urls = [
  "https://testimony-evaluated-lime-period.trycloudflare.com/auth/callback",
  "https://testimony-evaluated-lime-period.trycloudflare.com/auth/shopify/callback",
  "https://testimony-evaluated-lime-period.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[app_proxy]
url = "https://testimony-evaluated-lime-period.trycloudflare.com"
subpath = "frontends"
prefix = "apps"

[pos]
embedded = false
